version: "3.8"
services:

  # Applications

  backend-for-frontend:
    depends_on:
      - keycloak
    image: "ghcr.io/cynicdog/spa-spring-keycloak-oauth2/backend-for-frontend-service:latest"
    container_name: "backend-for-frontend"
    ports:
      - 9000:9000
    environment:
      - REACT_UI_URL=http://react-ui:4173
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/cynicdog

  react-ui:
    depends_on:
      - backend-for-frontend
    image: "ghcr.io/cynicdog/spa-spring-keycloak-oauth2/react-ui:latest"
    container_name: "react-ui"
    ports:
      - 4173:4173
    environment:
      - GITHUB_LOGIN_URL=https://keycloak:8080/auth/realms/cynicdog/protocol/openid-connect/auth?client_id=Iv23liOFyDyAWFYUsq1v&redirect_uri=http://localhost:9000/login/oauth2/code/*&response_type=code&scope=openid

  # Backing Services

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: "keycloak"
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=cynicdog
      - KEYCLOAK_ADMIN_PASSWORD=cynicdog
    ports:
      - 8080:8080